version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - .:/app