apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasklist-api
  template:
    metadata:
      labels:
        app: tasklist-api
    spec:
      containers:
        - name: tasklist-api:latest
          image:  obioma.azurecr.io/tasklist-api:latest 
          env:
            - name: DB_NAME
              value: mydatabase
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: mypassword
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"

