apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasklist-api
  template:
    metadata:
      labels:
        app: tasklist-api
    spec:
      containers:
        - name: tasklist-api
          image: obikiel/tasklist-api:latest  
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"

---
apiVersion: v1
kind: Service
metadata:
  name: tasklist-api-service
spec:
  selector:
    app: tasklist-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
